### ISSUE TITLE
How about iterating resources?

### ISSUE THREAD

**Issue by Smoren** [markrogoyski/itertools-php#15]
Hi Mark!

What do you think about the functionality for iterating resources in IterTools? For example, reading files. Something like this:

```php
class Resource {
    public static function readCsv(
        resource $stream,
        ?int $length = null,
        string $separator = ",",
        string $enclosure = "\"",
        string $escape = "\\"
    ): \Generator {
        while (($row = fgetcsv($handle, $length, $separator, $enclosure, $escape)) !== false) {
            yield $row;
        }
    }
}

$stream = fopen('path/to/file.csv');

foreach (Resource::readCsv($stream) as $row) {
    // ...
}

fclose($stream);
```

BTW, this may confuse the `Stream` namespace. What do you think, maybe rename `Stream` to `Fluent` or something else?

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for the feature suggestion. Give me some time to think about this and I'll get back to you. Sorry to make you wait.

Thanks for understanding.
Mark

**Comment by Smoren** [comment]
@markrogoyski 

Thank you for the answer.

I will wait for your decision.

**Comment by Smoren** [comment]
Hi @markrogoyski,

I thought about the renaming of `Stream` namespace and I have a very simple idea.

Maybe `Iterable` or `IterableWrapper`?

```php
Iterable::of($smth)
    ->pairwise()
    ->toArray();
```

I think it looks nice :)

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thanks for your suggestion and continued interest to improve IterTools. I have not released a new version that has the Streams feature yet, so it is still possible to make changes.

However, I would argue that Stream is right name for this for three reasons.

1) The word "stream" gives the image of things flowing together continuously, like the fluent chaining of methods together. Since the stream repeatedly processes the data, it is a form of iteration, and fits in with the theme of IterTools.

2) This is a common name for this functionality. See [Java Streams](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html), [C++ Streams API](https://jscheiny.github.io/Streams/api.html), numerous python stream libraries ([streams](https://github.com/9seconds/streams), [python-stream](https://github.com/fm100/python-stream), [streampy](https://github.com/tolsac/streampy), [Streams](https://github.com/ashbob999/Streams), [python-streams](https://github.com/GideonBuckwalter/python-streams), [python-streaming](https://github.com/dalonsog/python-streaming) , [pyStream](https://github.com/PiotrOpielski/pyStream), [pystreams](https://github.com/thomasahle/pystreams)), etc. 

3) It differentiates it clearly from the looping constructs in the library. IterTools now provides tools to power loops, and tools to process iterables in a functional pipeline, consisting of a source, zero-or-more operations, and a terminal operation.

These are my reasons. I'm happy to continue to discuss if you like. Thanks.
Mark

**Comment by Smoren** [comment]
Hi @markrogoyski,

Your arguments sound persuasive. I no longer insist on renaming.
Have you decided anything about including resources in IterTools?

**Comment by markrogoyski** [comment]
Hi @Smoren,

I think resources is too big a topic. See here: https://www.php.net/manual/en/resource.php. Many things return resources, including network calls and protocols, database handles, etc.

Maybe narrow the scope to iterating files or something would help refine the idea and make it workable. I can immediately think of iterating lines of a file, and lines of a CSV. Anything else you would consider? And maybe the namespace is `File` rather than `Resource` to clearly indicate the intent?

Thanks,
Mark

**Comment by Smoren** [comment]
Hi @markrogoyski,

I think namespace `File` is a good idea. I'll think about it's methods and their implementation.
